framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        routing:
            App\UseCase\Catalog\SyncSet\Input: async
            App\UseCase\Catalog\SyncAll\Input: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
